title: 'Hotels Licensing Board'
title-abbreviated: HLB
description: 'The Hotels Licensing Board website is an easy platform to search for types of hotels and  accommodations possessing a valid hotel licence and their locations'
url: 'https://www.hlb.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
collections:
    application-guidelines:
        output: true
    notices:
        output: true
resources_name: resources
paginate: 12
paginate_path: '/resources/page:num'
custom_css_path: /do-not-touch/theme-colors/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
favicon: /images/homepage/favicon-hlb.ico
google_analytics: null
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
